workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_ID: "com.example.readTheLabel" # schimbă cu ce ai în ios/Runner.xcodeproj
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Flutter build ipa
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - ta_adresa@email.com

